name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  APPLICATION: "koa-app"
  ENV: "Prod"
  IMAGE: ${{ secrets.IMAGE}}

jobs:
  setup-build-push:
    name: Setup, Build, Push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push Docker image
      run: |
        gcloud auth configure-docker europe-west10-docker.pkg.dev -q
        docker build -t tolgayakar/test:${{GITHUB.RUN_NUMBER}} .
        docker push tolgayakar/test:${{GITHUB.RUN_NUMBER}} 
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [setup-build-push]
    steps:

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        export_default_credentials: true  

    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.CLUSTER_NAME }}
        location: "europe-west10-a"

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/koa-app-deployment koa-app=tolgayakar/test:${{GITHUB.RUN_NUMBER}} -n application
